"""New Migration

Revision ID: 2ec52585569e
Revises: c3744b49a554
Create Date: 2021-08-08 15:28:26.518619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec52585569e'
down_revision = 'c3744b49a554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
