"""New Migration

Revision ID: bc318f8d329d
Revises: 2ec52585569e
Create Date: 2021-08-08 16:36:57.756594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc318f8d329d'
down_revision = '2ec52585569e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
